version: '3'
services:
  front_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front_prod.rule=Host(`dsp5-archi-f23-15m-g6.com`)"
      - "traefik.http.services.front_prod.loadbalancer.server.port=80"
      - "traefik.http.routers.front_prod.tls=true"
      - "traefik.http.routers.front_prod.tls.certresolver=le"
    networks:
      - workflow-network
      
networks:
  workflow-network:
    external: true
