version: '3'
services:
  front_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front_dev.rule=Host(`dev.dsp5-archi-f23-15m-g6.com`)"
      - "traefik.http.services.front_dev.loadbalancer.server.port=80"
      - "traefik.http.routers.front_dev.tls=true"
      - "traefik.http.routers.front_dev.tls.certresolver=le"
    networks:
      - workflow-network
      
networks:
  workflow-network:
    external: true
