version: '3'
services:
  front_pre:
    build:
      context: .
      dockerfile: Dockerfile.pre
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front_pre.rule=Host(`pre.dsp5-archi-f23-15m-g6.com`)"
      - "traefik.http.services.front_pre.loadbalancer.server.port=80"
      - "traefik.http.routers.front_pre.tls=true"
      - "traefik.http.routers.front_pre.tls.certresolver=le"
    networks:
      - workflow-network
      
networks:
  workflow-network:
    external: true
