version: '3'
services:
    backend_dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.backend_dev.rule=Host(`devapi.dsp5-archi-f23-15m-g6.com`)'
            - 'traefik.http.services.backend_dev.loadbalancer.server.port=9009'
            - 'traefik.http.routers.backend_dev.tls=true'
            - 'traefik.http.routers.backend_dev.tls.certresolver=le'
        networks:
            - workflow-network

networks:
    workflow-network:
        driver: bridge
        external: true
