version: '3'
services:
    backend_prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.backend_prod.rule=Host(`api.dsp5-archi-f23-15m-g6.com`)'
            - 'traefik.http.services.backend_prod.loadbalancer.server.port=9009'
            - 'traefik.http.routers.backend_prod.tls=true'
            - 'traefik.http.routers.backend_prod.tls.certresolver=le'
        networks:
            - workflow-network

networks:
    workflow-network:
        driver: bridge
        external: true
